### ISSUE TITLE
Undefined reference to fastforest

### ISSUE THREAD

**Issue by Amineleg** [guitargeek/XGBoost-FastForest#11]
Hello.
I tried to test this library using the code sample provided in the readme but I keep getting the undefined reference to fastforest error.
Do you have any idea what could be the origin of the issue?
![image](https://user-images.githubusercontent.com/43117849/100810566-0ebd4f80-3439-11eb-8ac1-49ba723f41fe.png)

**Comment by guitargeek** [comment]
Hi! You mean the first C++ example from the README? I just tried it again myself and it work for me, after installing fastforest with `make install` of course. How did you try to compile the test? You remembered the `-lfastforest` flag to link against the library?

I compiled it like this with gcc:
```
g++ -o test test.cpp -lfastforest
```

**Comment by Amineleg** [comment]
Hello, thanks for the answer. it seems that my compiler didn't find where the library was installed. I reinstalled fastforest and now it is working.
Thanks again.
