### ISSUE TITLE
Linking error for build C++ test

### ISSUE THREAD

**Issue by jiaboli007** [guitargeek/XGBoost-FastForest#12]
I got the following linking error when I compile my test code:
undefined reference to `fast forest::loadtxt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'

Here is my test code:

#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
#include <ctime>
#include "fastforest.h"
#include <cmath>

int main() {
std::vector<std::string> features{"f0","f1","f2","f3","f4","f5","f6","f7","f8","f9",\
                                  "f10","f11","f12","f13","f14","f15","f16","f17","f18","f19",\
                                  "f20","f21","f22","f23","f24","f25","f26","f27","f28","f29"};

    const auto fastForest = fastforest::load_txt("model.txt", features);

    std::vector<float> input{1, 0, 6, 4, 0, 0, 0, 1, 6, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 6, 0, 0, 0, 0, 0, 0, 0};

    float bond_length = fastForest(input.data());
    std::cout << "Bond Length = " << bond_length << "\n";
}

Any help will be highly appreciated! Thanks.

**Comment by guitargeek** [comment]
Hi @jiaboli007! How did you install the fastforest library, and how are you building your test code?

I compiles fastforest with `make install`, took your code and compiled it with `g++ -o test test.cc -lfastforest`. No problem!

Did you remember the `-lfastforest` flag to link against the library?

**Comment by guitargeek** [comment]
Was the problem solved? Can the issue be closed?

**Comment by guitargeek** [comment]
I'll close this CMake support issue.
