### ISSUE TITLE
multiclass support

### ISSUE THREAD

**Issue by svb688** [guitargeek/XGBoost-FastForest#7]
Very simple to use so far, I was able to use the library for binary classification and it is speedier than m2cgen. I noticed that the return type of operator() is just float. Is it possible to return a vector of probabilities (for multiclass classification) such as model.predict_proba()? My task involves sampling from these probabilities.

**Comment by guitargeek** [comment]
Hi again! For now it was not possible to do multiclassification because I didn't need it and nobody asked for it. But it's not hard to implement, which I just did. Please check the README for instructions and let me know if it works for you.

**Comment by guitargeek** [comment]
Hi! Can this issue be closed?

**Comment by guitargeek** [comment]
I'll close it, since fastforest now supports the multiclassification. Please open a new issue if you have further problems.

**Comment by svb688** [comment]
Thanks again!
